version: '3.8'
services:
  web:
    build: ./apps/web
    ports:
      - "3000:3000"
  api:
    build: ./apps/api
    ports:
      - "8000:8000"
  auth:
    build: ./services/auth
    ports:
      - "7000:7000"
